package com.heag.rcpc.mapper;

import com.heag.rcpc.model.PcOptions;
import com.heag.rcpc.model.PcOptionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PcOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int countByExample(PcOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int deleteByExample(PcOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int insert(PcOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int insertSelective(PcOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    List<PcOptions> selectByExample(PcOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    PcOptions selectByPrimaryKey(Integer oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PcOptions record, @Param("example") PcOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PcOptions record, @Param("example") PcOptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PcOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_options
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PcOptions record);
}