package com.heag.rcpc.model;

import java.util.Date;

public class PcEvaluateRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.relation
     *
     * @mbggenerated
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.evaluator
     *
     * @mbggenerated
     */
    private String evaluator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.emailstatus
     *
     * @mbggenerated
     */
    private String emailstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.emailSendtime
     *
     * @mbggenerated
     */
    private Date emailsendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.completestatus
     *
     * @mbggenerated
     */
    private String completestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.completetime
     *
     * @mbggenerated
     */
    private Date completetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.isdelete
     *
     * @mbggenerated
     */
    private Byte isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluaterelation.aid
     *
     * @mbggenerated
     */
    private Integer aid;
    
    private String ename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.id
     *
     * @return the value of pc_evaluaterelation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.id
     *
     * @param id the value for pc_evaluaterelation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.eid
     *
     * @return the value of pc_evaluaterelation.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.eid
     *
     * @param eid the value for pc_evaluaterelation.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.relation
     *
     * @return the value of pc_evaluaterelation.relation
     *
     * @mbggenerated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.relation
     *
     * @param relation the value for pc_evaluaterelation.relation
     *
     * @mbggenerated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.evaluator
     *
     * @return the value of pc_evaluaterelation.evaluator
     *
     * @mbggenerated
     */
    public String getEvaluator() {
        return evaluator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.evaluator
     *
     * @param evaluator the value for pc_evaluaterelation.evaluator
     *
     * @mbggenerated
     */
    public void setEvaluator(String evaluator) {
        this.evaluator = evaluator == null ? null : evaluator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.email
     *
     * @return the value of pc_evaluaterelation.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.email
     *
     * @param email the value for pc_evaluaterelation.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.emailstatus
     *
     * @return the value of pc_evaluaterelation.emailstatus
     *
     * @mbggenerated
     */
    public String getEmailstatus() {
        return emailstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.emailstatus
     *
     * @param emailstatus the value for pc_evaluaterelation.emailstatus
     *
     * @mbggenerated
     */
    public void setEmailstatus(String emailstatus) {
        this.emailstatus = emailstatus == null ? null : emailstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.emailSendtime
     *
     * @return the value of pc_evaluaterelation.emailSendtime
     *
     * @mbggenerated
     */
    public Date getEmailsendtime() {
        return emailsendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.emailSendtime
     *
     * @param emailsendtime the value for pc_evaluaterelation.emailSendtime
     *
     * @mbggenerated
     */
    public void setEmailsendtime(Date emailsendtime) {
        this.emailsendtime = emailsendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.completestatus
     *
     * @return the value of pc_evaluaterelation.completestatus
     *
     * @mbggenerated
     */
    public String getCompletestatus() {
        return completestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.completestatus
     *
     * @param completestatus the value for pc_evaluaterelation.completestatus
     *
     * @mbggenerated
     */
    public void setCompletestatus(String completestatus) {
        this.completestatus = completestatus == null ? null : completestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.completetime
     *
     * @return the value of pc_evaluaterelation.completetime
     *
     * @mbggenerated
     */
    public Date getCompletetime() {
        return completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.completetime
     *
     * @param completetime the value for pc_evaluaterelation.completetime
     *
     * @mbggenerated
     */
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.remark
     *
     * @return the value of pc_evaluaterelation.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.remark
     *
     * @param remark the value for pc_evaluaterelation.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.isdelete
     *
     * @return the value of pc_evaluaterelation.isdelete
     *
     * @mbggenerated
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.isdelete
     *
     * @param isdelete the value for pc_evaluaterelation.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.createdate
     *
     * @return the value of pc_evaluaterelation.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.createdate
     *
     * @param createdate the value for pc_evaluaterelation.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluaterelation.aid
     *
     * @return the value of pc_evaluaterelation.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluaterelation.aid
     *
     * @param aid the value for pc_evaluaterelation.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getEname() {
		return ename;
	}
}