package com.heag.rcpc.model;

import java.util.Date;

public class PcEvaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.ename
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.dname
     *
     * @mbggenerated
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.num
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.completeNum
     *
     * @mbggenerated
     */
    private String completenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.isdelete
     *
     * @mbggenerated
     */
    private Byte isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_evaluate.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.eid
     *
     * @return the value of pc_evaluate.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.eid
     *
     * @param eid the value for pc_evaluate.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.aid
     *
     * @return the value of pc_evaluate.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.aid
     *
     * @param aid the value for pc_evaluate.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.ename
     *
     * @return the value of pc_evaluate.ename
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.ename
     *
     * @param ename the value for pc_evaluate.ename
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.dname
     *
     * @return the value of pc_evaluate.dname
     *
     * @mbggenerated
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.dname
     *
     * @param dname the value for pc_evaluate.dname
     *
     * @mbggenerated
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.email
     *
     * @return the value of pc_evaluate.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.email
     *
     * @param email the value for pc_evaluate.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.num
     *
     * @return the value of pc_evaluate.num
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.num
     *
     * @param num the value for pc_evaluate.num
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.completeNum
     *
     * @return the value of pc_evaluate.completeNum
     *
     * @mbggenerated
     */
    public String getCompletenum() {
        return completenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.completeNum
     *
     * @param completenum the value for pc_evaluate.completeNum
     *
     * @mbggenerated
     */
    public void setCompletenum(String completenum) {
        this.completenum = completenum == null ? null : completenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.remark
     *
     * @return the value of pc_evaluate.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.remark
     *
     * @param remark the value for pc_evaluate.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.isdelete
     *
     * @return the value of pc_evaluate.isdelete
     *
     * @mbggenerated
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.isdelete
     *
     * @param isdelete the value for pc_evaluate.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_evaluate.createdate
     *
     * @return the value of pc_evaluate.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_evaluate.createdate
     *
     * @param createdate the value for pc_evaluate.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}