package com.heag.rcpc.model;

import java.util.Date;

public class PcResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.rid
     *
     * @mbggenerated
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.qid
     *
     * @mbggenerated
     */
    private Integer qid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.rresult
     *
     * @mbggenerated
     */
    private String rresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.evaluator
     *
     * @mbggenerated
     */
    private String evaluator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.isdelete
     *
     * @mbggenerated
     */
    private Byte isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_result.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.rid
     *
     * @return the value of pc_result.rid
     *
     * @mbggenerated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.rid
     *
     * @param rid the value for pc_result.rid
     *
     * @mbggenerated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.qid
     *
     * @return the value of pc_result.qid
     *
     * @mbggenerated
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.qid
     *
     * @param qid the value for pc_result.qid
     *
     * @mbggenerated
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.aid
     *
     * @return the value of pc_result.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.aid
     *
     * @param aid the value for pc_result.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.eid
     *
     * @return the value of pc_result.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.eid
     *
     * @param eid the value for pc_result.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.id
     *
     * @return the value of pc_result.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.id
     *
     * @param id the value for pc_result.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.rresult
     *
     * @return the value of pc_result.rresult
     *
     * @mbggenerated
     */
    public String getRresult() {
        return rresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.rresult
     *
     * @param rresult the value for pc_result.rresult
     *
     * @mbggenerated
     */
    public void setRresult(String rresult) {
        this.rresult = rresult == null ? null : rresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.evaluator
     *
     * @return the value of pc_result.evaluator
     *
     * @mbggenerated
     */
    public String getEvaluator() {
        return evaluator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.evaluator
     *
     * @param evaluator the value for pc_result.evaluator
     *
     * @mbggenerated
     */
    public void setEvaluator(String evaluator) {
        this.evaluator = evaluator == null ? null : evaluator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.remark
     *
     * @return the value of pc_result.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.remark
     *
     * @param remark the value for pc_result.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.isdelete
     *
     * @return the value of pc_result.isdelete
     *
     * @mbggenerated
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.isdelete
     *
     * @param isdelete the value for pc_result.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_result.createdate
     *
     * @return the value of pc_result.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_result.createdate
     *
     * @param createdate the value for pc_result.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}