package com.heag.rcpc.mapper;

import com.heag.rcpc.model.PcEvaluate;
import com.heag.rcpc.model.PcEvaluateExample;

import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PcEvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int countByExample(PcEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int deleteByExample(PcEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int insert(PcEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int insertSelective(PcEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    List<PcEvaluate> selectByExample(PcEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    PcEvaluate selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PcEvaluate record, @Param("example") PcEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PcEvaluate record, @Param("example") PcEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PcEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_evaluate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PcEvaluate record);

	int batchUpdateById(ArrayList<PcEvaluate> idList);
}