package com.heag.rcpc.model;

import java.util.Date;
import java.util.List;

public class PcQuestion {
	private List<PcOptions> pcOptions;	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_question.qid
     *
     * @mbggenerated
     */
    private Integer qid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_question.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_question.qname
     *
     * @mbggenerated
     */
    private String qname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_question.qtype
     *
     * @mbggenerated
     */
    private Integer qtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_question.orderid
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_question.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_question.isdelete
     *
     * @mbggenerated
     */
    private Byte isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_question.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_question.qid
     *
     * @return the value of pc_question.qid
     *
     * @mbggenerated
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_question.qid
     *
     * @param qid the value for pc_question.qid
     *
     * @mbggenerated
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_question.aid
     *
     * @return the value of pc_question.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_question.aid
     *
     * @param aid the value for pc_question.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_question.qname
     *
     * @return the value of pc_question.qname
     *
     * @mbggenerated
     */
    public String getQname() {
        return qname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_question.qname
     *
     * @param qname the value for pc_question.qname
     *
     * @mbggenerated
     */
    public void setQname(String qname) {
        this.qname = qname == null ? null : qname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_question.qtype
     *
     * @return the value of pc_question.qtype
     *
     * @mbggenerated
     */
    public Integer getQtype() {
        return qtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_question.qtype
     *
     * @param qtype the value for pc_question.qtype
     *
     * @mbggenerated
     */
    public void setQtype(Integer qtype) {
        this.qtype = qtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_question.orderid
     *
     * @return the value of pc_question.orderid
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_question.orderid
     *
     * @param orderid the value for pc_question.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_question.remark
     *
     * @return the value of pc_question.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_question.remark
     *
     * @param remark the value for pc_question.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_question.isdelete
     *
     * @return the value of pc_question.isdelete
     *
     * @mbggenerated
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_question.isdelete
     *
     * @param isdelete the value for pc_question.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_question.createdate
     *
     * @return the value of pc_question.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_question.createdate
     *
     * @param createdate the value for pc_question.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

	public void setPcOptions(List<PcOptions> pcOptions) {
		this.pcOptions = pcOptions;
	}

	public List<PcOptions> getPcOptions() {
		return pcOptions;
	}
}