package com.heag.rcpc.mapper;

import com.heag.rcpc.model.PcQuestion;
import com.heag.rcpc.model.PcQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PcQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int countByExample(PcQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int deleteByExample(PcQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer qid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int insert(PcQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int insertSelective(PcQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    List<PcQuestion> selectByExample(PcQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    PcQuestion selectByPrimaryKey(Integer qid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PcQuestion record, @Param("example") PcQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PcQuestion record, @Param("example") PcQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PcQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_question
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PcQuestion record);

    List<PcQuestion> selectQuestionAndOptions(PcQuestion record);

	List<PcQuestion> selectQuestionContext(Integer aid);    
}